name : CI/CD Pipeline
on:
  push:
    branches: [main]
  jobs:
    build:
      runs-on: windows-latest
      steps:
        -uses: actions/checkout@v4
        -name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
        -name: set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version:'16'
        -name: Build React app
        run : |
          cd ui.frontend
          npm install
          npm run build
        -name: Build AEM Package
        run: mvn -B clean install
        -name: Deploy to AEM
        run: |
         mvn -PautoInstallPackage -Daem.host=localhost -Daem.port=4502 
        -Daem.username=admin -Daem.password=admin
        -name : Run Groovy Script
        run: |
          curl -u admin:admin -F file=@groovy/report-content-usage.groovy -F name=report -F cmd=upload http://localhost:4502/etc/groovyconsole/post.json
          curl -u admin:admin http://localhost:4502/etc/groovyconsole/run.json?name=report
        -name: Upload Report Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: content-usage-report
          path: content-usage-report.txt

